// Run after regenerating the project. Reimports its binary into a separate temporary Ghidra project.
import {readFile,readdir,mkdir,writeFile,unlink} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {spawn} from 'node:child_process';
import {createHash} from 'node:crypto';
const root=resolve(import.meta.dirname,'..');
const id=process.argv[2];
if(!/^[a-f0-9-]{36}$/.test(id||''))throw Error('Usage: node scripts/verify-project.mjs <project-uuid>');
const dir=join(root,'data',id),audit=join(dir,'verification');
await mkdir(audit,{recursive:true});
const project=JSON.parse(await readFile(join(dir,'project.json'),'utf8'));
if(project.status!=='ready')throw Error('Project must have a completed analysis');
const files=await readdir(join(root,'.runtime'));
const ghidra=process.env.GHIDRA_HOME||join(root,'.runtime',files.find(x=>x.startsWith('ghidra_')&&!x.endsWith('.zip')));
const java=process.env.JAVA_HOME||join(root,'.runtime',files.find(x=>x.startsWith('jdk-')),'Contents','Home');
const reportPath=join(audit,'report.json');
await unlink(reportPath).catch(e=>{if(e.code!=='ENOENT')throw e;});
const snapshot=await readFile(join(dir,'result.json'));
await writeFile(join(audit,'reference.json'),snapshot);
const child=spawn(join(ghidra,'support','analyzeHeadless'),[audit,'reference','-overwrite','-import',join(dir,'input.bin'),'-scriptPath',join(root,'scripts'),'-postScript','VerifyWeb.java',join(audit,'reference.json'),reportPath,'-analysisTimeoutPerFile','300','-max-cpu','2','-deleteProject'],{env:{...process.env,JAVA_HOME:java,GHIDRA_HEADLESS_MAXMEM:'2G',JAVA_TOOL_OPTIONS:`-Dapplication.settingsdir="${join(audit,'settings')}" -Dapplication.cachedir="${join(audit,'cache')}" -Djava.io.tmpdir="${audit}"`}});
let log='';child.stdout.on('data',b=>log+=b);child.stderr.on('data',b=>log+=b);
const exitCode=await new Promise((res,rej)=>{child.on('error',rej);child.on('close',res);});
await writeFile(join(audit,'engine.log'),log);
if(exitCode!==0)throw Error('Reference Ghidra failed; see '+join(audit,'engine.log'));
const report=JSON.parse(await readFile(reportPath,'utf8'));
report.binarySHA256=createHash('sha256').update(await readFile(join(dir,'input.bin'))).digest('hex');
report.resultSHA256=createHash('sha256').update(snapshot).digest('hex');
report.binaryName=project.name;
report.method='Independent headless re-import and DecompInterface with default options plus program compiler specification. Compares pseudocode and exported instructions; not a desktop UI comparison.';
await writeFile(reportPath,JSON.stringify(report,null,2));
console.log(JSON.stringify(report,null,2));
if(!report.passed)process.exitCode=1;
